### PR TITLE
tlsrestrict: Remove unnecessary type conversions.

### PR DESCRIPTION
**Pull request by JeremyRand**
Found by static analysis.

### CODE REVIEW

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hugo Landau:
> hlandau approved this pull request.
> 
> ACK assuming Travis passes.

Can you specify the commit hash that you reviewed?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZSbW0AAoJELPy0WV4bWVwrQ0P/2cA+In9G7UrHJizsRmgJgj8
Awxidh6WkbzagHpglf61Wf+PW2jh3mHhRQ9/wSzoRyN+tZFx88PveBh1lk8uOefq
4SfW3XMO27zgjKUbGhNN1Q1FLKgg77J2b/4rC9y2Q8fhecgR6K2jhLTmyKJHZ9bw
/9tO9jQtX8wDU/O3AYKyw8yhD3t1BCkMmyXchdn1f8clJIzX2eI2/5zA21ClUuOB
KzSoWPdtBBPmDak42Fna/+c4yxufWUi3Tlgb0Ft91gulXMmUMuqImew50UnvJ3SR
8awgTrUrRQ4B4RgdK2/Apqhown2pjJ9wf1V4Ojx5mOiluuU/5tfU+xBcV8q2d7uf
nhCkFC2sQFjnOxvsmUeGLbXRGE0gDwxaZ+nXQH2k2VkMFx6b91yc3yv0OGy13OQE
OfjHU3JDvLQWDoF8/EsY7FtHq2nQTrGjXR4dAQAIf2oPH922hiUBiBvRkfe9rZQO
V+A3cogh+L18I2Xbp83xedcAclcmxrC1827/p+Tk/EhM3kuduzT8xcvyiU5nQjB2
kmkt7q89L5AsYBY8D9mTb7c84kyqWqqbPZgCO/303CuuxKdXLuB+8674r683gxDt
YKQFgZfpLpsStt2rcH6ubabHSIuivyAFbGx02Tl60W6dhrPE9RTqNdHwDASwkFdf
hyk3BHGn3nDcwZqPpX2z
=z/5g
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
I did it via GitHub's review thingy, I'm fairly sure it detects changes.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hugo Landau:
> I did it via GitHub's review thingy, I'm fairly sure it detects
> changes.

GitHub's review system doesn't generate emails with that info, so it
doesn't produce DKIM signatures of the commit hash.  Including a
commit hash in an ACK comment does produce DKIM signatures, which is
slightly more reliable.  Also the Bitcoin Core folks require commit
hashes with ACKs, and I tend to defer to them on this stuff.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZTI7SAAoJELPy0WV4bWVwtPoP/0AgwKOkAdKtH5ZkqJqQzdDZ
1kjWRefwvv4ppfxhEg/YKHf6AhE+t57TdIraqY0finC5hxaWv4GUe+6rpIZLmZwp
EJNmjNx6Rrgn48NmRsRAs4sMth/JnP5bDOn+UbXNp4QFrMLnq+BF8hjgQczP6r7T
OnW+3MpBT9JV8mMuty4R+QckWQFXML+67pazSS/1fhPsrVPgbOPhW3ydZDvLEvFO
ijCE56IypTBxKDTghvnlyCjMzGpxdOubO9bqhdkRraT/1iLuJx1YdaxHOj8lCEpU
/FGYuZpMnnBVoX3J7BDmVvtyMFj5rqryUsso1Il+KwxzocgmH2INpEHcMldD29Gn
Mg/tR5w9sdVxOnPcakztMF/aeYICtZ2wfET3ksjq19SMRu9P4OKXNj+HMXt68o3O
OtecekcEh0Xr+fDrQwD/mjUg086h6G0bTkcfh/piffoIAxQZhI7Tn40Jv5+9iD03
V/eHfeu1qociMExplIRMs1kEHVT/xNFs5xPHXoA5SFejJCzepTPCGbuDzmd4Rcoh
iEHiCFMKcZMDnDXZh0Qi6PJzyYIp55c2vVpdNie8sZoR6k3BIdZhWUYZEUVo7v3r
PQ+qRqk59+GnO7ywqvZ7xlW57Io9T8jNe96LV4+APTqyz4t9QW8/iOBgJBqK9EtU
N/SptyV+yvfpdsyA8LAH
=n9St
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
I have no idea how GitHub's DKIM signature has suddenly become relevant to this.

What threat model are you concerned about here?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hugo Landau:
> I have no idea how GitHub's DKIM signature has suddenly become
> relevant to this.
> 
> What threat model are you concerned about here?

Bitcoin Core's rationale is at
https://github.com/bitcoin/bitcoin/pull/7185 .  For example:

> without a reference to which commits were ACK'd it's impossible to 
> tell what if anything was changed

The Bitcoin Core devs didn't mention DKIM, although I do think it's a
slight additional bonus.  Hope that helps explain.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZTtliAAoJELPy0WV4bWVw5lYP/2AWUtsnjLs2SKWTEwQk7V8h
bhIwGueTm1u9D7fLtuRHhVcqSlTGDyRyeWPmSeMLS01mxsF4nauQWHpXUfiEs1cU
V1IkrvyRQ3huBDWm+SpuHKOLAZVzwifgO+7PwDORIO7lAf5IIoXb/hhv3EhziE9a
j7dvltdMljUU2emjMOfU1+8AYShoiDirgWGHentwdawmIuVZP7lIswSsmqc+OO6J
Xoppt3MfbokFagX8LQ44ZPSO1DCbbaT+obZyCae/oPHBE9ZHtRIXTtLXC10uTcJI
qOVXkDd1KCIA+9og64PTe83g0Q/y99Td8bH1PuUTLWyaLsGhS921VnOsNLuJhpiR
6bgYO0ope1VJUu73dB3PrlfPI0AHju39jPEYm4b8lDOU0OIo7xz2EDH0lEaKmBQz
F57Omlew6O+nAoWbEvcdgxJP4ePGM4qEjJEk7mfl3q81ISHDY5nlccsm7U4MRDSA
CTs17g8F3knHQ94TlCUdNEOHKj8Q33k6aJ55NVjCathMTjGtX3SFa0xMht09s5LG
iqxCQHggNeC7XUL1wAKXBJPBAm/wYO5/up5+F3/btBN8WTXKv2b/f5PnB8u7RVMV
xIGnEGb7wnr8pWCDyHr4IJz52mEI5fngXeIOTWnC/qIm0Izy4YtjtyhGvVqdJeN9
AhA412pkMgDwFhHiJ6PR
=nvFN
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Doing a quick test to see what happens to the review if I rebase.
Prior to the rebase, @hlandau's review was applicable to
da471135df0ca84c3a184623462f0fe5e769b92f .

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZV2CqAAoJELPy0WV4bWVwZJUQAN6zt6SwMUXIQqflxZrGZD1Y
iNnFH9ZxXTXEei/umLQI9Go5YgE4aalUaJ8Pl6VUi+CGKqcqsvp2RcjB9+UyeUSp
ha16NRFLVQ+/pgDcvx6jx2AlaM2ubllqmEegjoFMdhVxHIOKpA5ZzYN2kCmWM6Gn
mYzEmHoKuPb6wugIp5QR8mXY7qtGH3eb++t/P/v7ChF14r7oPhse/LxObs2s0Fh9
XmTRLt/PAgLWsi7F1H+X1StXgAVsgMdvZd51SkUbLtvBE6lFV+yKwWck9WIKbYzS
UuYNnlS8W8ZhbYIXjuLTfqABwoABRxr4O45PEYjv08F71jlZJrzJ/UCynwXLBrs1
FJ7KPe3NYW8daYpF9wY89uiuQvEnO2Pd0lPeUtD09bFblYSgc4vdVOROd/bJhAVL
zpgIYLOuWRPmEmY+NxTVEx5Zc4OW8aGD/0r9NZvke4eGH9KppG+FibRf0oHGGTzQ
mA2FbHAyVbOlVFtz21K8ezQKRWXL+tvcxL4yKrS9iBTt5D64l6/nzZuZQ+qRR/OE
v+oTdCVWE5edV7GYc0QDtGdYtcC52Dj36Fj2KULA+WLgwhvDgt+9BOmk4iEMmtRE
yekXPRjkDMwRmvUTWtDPfUnhaM024vteMpJXzSNt6/CZW33RoNWHgIBxfNPblS62
onTmwy6VJDwxrWxShgUQ
=+3Q0
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@hlandau I see a major advantage to using a commit hash directly.

Your review did preserve the correct commit hash after I rebased, but
the link broke.  Your link points to
https://github.com/namecoin/ncdns/pull/26/files/da471135df0ca84c3a184623
462f0fe5e769b92f
, which is a broken link after my rebase.

My link points to
https://github.com/namecoin/ncdns/commit/da471135df0ca84c3a184623462f0fe
5e769b92f
, which is still a valid link after my rebase.

So there's a strong usability advantage to using a commit hash in the
ACK/NACK message compared to relying on a GitHub review to convey the
commit hash.

Is that good enough for you?  :)

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZV2NvAAoJELPy0WV4bWVwTL8QANN+7iDJAmRwqZAV2WBbgMF+
bnBHVlLyaVIm0O59KQGyUe6QmbNH4UXfjEmI5SK1tORCV441YKuSY1Zav2IvTwVx
vpA7RbFMfJyNL5tecbq/01hey124JgRkkkfDGm2RNm1nLny+B7DTpopH/yJouTHN
aOEDNn523GUSfYGaRM1omVxOkJmx0NyC+A0WIY/L4Tqb0fyH0wTvG10wkOpSgyl8
73dgDninAcYYJHENyWsjKJMU1ouixw1YeF/TTxQex5Wl457OTScErBuT9nCF0jkl
RvreCuwzKwHKw6i0iIA5+j0+Pvx+WboslnYQnvFDPLddioYizF0rHlzEBoqJ2bJD
AWj7fY/3V4PcP8j/i5aKGDcsj/2aIu7DbYlLhDCMjkjyGpqNdby+mNWoO0efn+SF
dM2/HqBWX/A4GzloEFURWxJ+mxsW38fMqMCfSFEyU3Hxcc9Oxu0ta0jDCoPZMuO3
Ze1+UM2MhQ5n2Dlrjfs5uwmvaOSXgHcrurN6M0c9XSGSDvdGzPHloznJBwv+6lom
Sc5WS/leZMcSH0opDlOjxLWbAb7pYXVOcaXOGd5uM4Eg6dUAw1yEccDsJJxZVuIJ
meiFeE3EB41elzSjKI5kRj0iRJF5n/vHRWVllG2skLrE/mDXUvnRNXlKn+TKnk69
lO55w2CxikYu9q1zK2+d
=TWLZ
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/ncdns/pull/26/commits/5007619deaa0b16311d361119f3cf010650b3dad

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@hlandau can we revert 5007619deaa0b16311d361119f3cf010650b3dad ?  It
appears to have been generated by the GitHub web UI and therefore
isn't OpenPGP-signed.  In the future, just ask the PR submitter to
rebase if needed.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZaSoEAAoJELPy0WV4bWVwFFkQALnM3vjLMu1xL6YVVLqt2vDf
nC6nshDy7GasvpxkfNcD8bli7QfJq7yavnrFst/xnpfKHVUrxbNWxbYPCWHS++sv
66FTWtMfHCdVB1mSwJvCv5SMrn64owjyePaaqvHlDR2d42XVMitvW6Tlfb7PQ/K8
ym22OI1BEUEGxIqAEQosoq1u5C8fU2TiyBtM7kmnPdfAZ0k33MGZ8es9i6dAeDHq
hCQ+ruhp29E8yoIBt992bhzgb0jF/vJFDJLZCpNqEvkv5bMhfspvr1ymTLQoykjR
eCklpM9QDiyD81Lkj+SOJBbZBQ2f27K/i3YJHh9j3T7hxdxsAVxOsk77grJB/Hca
gfxXujYuezkXNCtHZnvQrbT3ADRz9psqPqNEsun9lG5LLgr3O4afH8GkCYOoRjpm
PdAZsU6aXz50Kezr2UU9blcJd6GBEmHooyNJ/JPrqIAdA4agyAtV+XvDFpKg7KQm
edQCZgSI5ZTzGjm/08dYoHD1Q34XgN+9Y2a2b6yZexKeXIOh29SYB9i5n1sxxJiM
tqHQM3G5WAM4gVb6H4naAwgkwVVDn4/fghnKwtZXgJcWsFxz1ufFhiV1jIZn9pUf
iGwH908zWoRChGfH4nmKkE0uTaDPJ4TeG9+T9uvJAjjwONfbPdBuqOsMJUP1TbY6
aGyo1qnr92T1UIBSxHSQ
=zEW8
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
Up to you what you do with your own branches.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@hlandau any chance you could ACK
8ae0a719bad2e3c8b902244a1a2728dce58cf16f ?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZerjdAAoJELPy0WV4bWVwsUoQAIWI6Ei7OKUOnGDFVJOx7qwJ
I94KX17WSFeX7rNoQO9XUgB9EBj/iR90XJZtdx0+7R+l3ajiCf2fOx0+64rMMt2M
hvn3b5ZFvEg6QjJdhFmED8gBOITHljzWDbL+x6Fk421LRzqwrfU5Dt7AhXokTaJz
x5DUeibg/TmzOD7B1mM8qp68IVqNLlCO+x5TAJd9h4+0bIGwlfeT6hE3yy/k0N5e
HhOb5M3QVZQ3uGHhHtqf9GVLmk0GC0DAKfJV1QpfK2FWyN+yMCPRU12WLNCIdq2m
tHvV+TKbijYdPzguV0oQpym9MUlhplgO2Hsy4HrdyqsHKeh7IOTywRqGtC+25S3N
An4oKIAStfjR+yoHwYr2hmZd9rufen71MEHN/WWmazkcfT/E7C+jCROyP23YpP6L
d/9H4mQf8Es3ychVDx73f2UDHpnSdIbHiS+Jxo1mu0EvaadcIvujD069HRJhHGrB
6SOzb1IfLfXZ+LGqXoaxeNRcYuRyV2O13aeJtUt3UOgTaxUrZK25P9O1/ixnMUCG
Em54nmeMSR6o3izSOtiZxr8hRi0L19pkgxbU7TkheL/2P7tUPl/zxZx2idO/jssF
e/mfxqWBNzmV95/3/YDbiyikCvPH9eioM/fY9vukdEOFIOSC4CbVy6sswtcg5tH1
J7VqILyy3BZvabiuDTMm
=E5zC
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
Needs update.

**Comment by JeremyRand** [comment]
@hlandau what update is needed?  Just rebasing against master, or something else?

**Comment by hlandau** [comment]
GitHub says it's out of date. Just rebase, I guess.

**Comment by JeremyRand** [comment]
> GitHub says it's out of date. Just rebase, I guess.

@hlandau I think that warning from GitHub is superfluous; it doesn't seem to indicate an actual merge conflict (it just shows up whenever the PR branch is forked from a commit older than the HEAD of the branch the PR is made against).  Rebasing PR's every time that warning shows up would be a significant time sink, with no benefit that's obvious to me.  (It would make sense in a workflow where GitHub-generated merge commits are trusted, but that's not our workflow.)

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

JeremyRand:
>> GitHub says it's out of date. Just rebase, I guess.
> 
> @hlandau I think that warning from GitHub is superfluous; it
> doesn't seem to indicate an actual merge conflict (it just shows up
> whenever the PR branch is forked from a commit older than the HEAD
> of the branch the PR is made against).  Rebasing PR's every time
> that warning shows up would be a significant time sink, with no
> benefit that's obvious to me.  (It would make sense in a workflow
> where GitHub-generated merge commits are trusted, but that's not
> our workflow.)

@hlandau is anything needed before we merge this?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZr/ZxAAoJELPy0WV4bWVwtxoP/2mgHfPoLKhbJvOdspFI5hsU
BGnONlj26CZ/KrgdZ2FXW0SpYY3W0q+xc+7eBvYvSNAlbWQiGqWdrweT3wngyoI3
T79rrXw/oXUcS+Y8JxN5r1bvXDembQCSFgtCOMWAQpBquwq7SvCzgh8eht42SXs9
4Wy8/qsuWxdTaF94+MIeN7drJdSOJyUMT1iSoUgrqG7FOYV9F+kGKHLizVau+TKf
qedblkKcfdkCEEfd5t0rlyhRsyQxo43sNWZ2oMNBISZN/jn8vncoB5oW4ZiIGRPB
mrCXxB8DPppx5AlsIIGaNH9ave4Dx/RHoJGdo6z63t2jHkOc/i4DKm9ltK2lDzfF
ffhqnRGh9iWJardN8ngQwPkHtMX+B4xM7WbcGwV5aGl/eVQ281usN6SQyWAkK8yM
yW+pDvA0KtPXsY8+aUsmcgSQdm0cP/DcV64Do402CLpJ7Kn4xEeXpYEk3RC9ISKE
nbIw6MIirgNQdwvQXVKYAsWUp9dCUdsP2w1NJwuG80od8hANHBz4cV5Thn6tT2bj
1uOB45FOF0mxH3QVV6Hm+YWXH8h8vsIsXxpJtuZMo8F6/89t8pWxaDO/+igtrNZG
S6KCXY28FuEXmkF5KT5HPgWTQo2RMu1Crh83wkVqzMBXZ6Kl1v3ZSpEZfxXrGPkh
/QhPIuG/yuh8lFHlJaBI
=KIOx
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
Jesus christ this still isn't merged?

ACK https://github.com/namecoin/ncdns/pull/26/commits/8ae0a719bad2e3c8b902244a1a2728dce58cf16f
or ACK https://github.com/namecoin/ncdns/pull/26/commits/5007619deaa0b16311d361119f3cf010650b3dad
or what you like.

**Pull request merged**
