### PR TITLE
Travis CI: Reduce Gox parallelism to 3

### PR DESCRIPTION
**Pull request by JeremyRand**
Travis VM's have 2 cores.

### CODE REVIEW

**Comment by hlandau** [comment]
https://github.com/namecoin/ncdns/pull/29/commits/664ccc6a111a5b052549a6d77485d3f5ede3923a

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@hlandau Can we revert 08e7c0db0e18533a402b162632f6e98ab5345fce ?  It
doesn't appear to be OpenPGP-signed.  (Feel free to ask me to rebase
if needed.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZd/KjAAoJELPy0WV4bWVw5soP/RImJcQeZXz/9tOiwkVM+L0C
c6C1Yhgc1jvGP/EYvL6TXG1qr5oY+8Wjx2Ycb6VhLFzVL7Bxal3nY8p7au8MngnJ
T3xC39kldd+rqsx+XSvYyxwqKBd96SIa7Cwmlp9sWPOaX6K4Y1zwhne27IuR1QKQ
TXVaxNuixa2eceYmvymBRN9d/kfRz+e7jNJng0ThTO0vphlqGMAdFYb/4BfnsseI
wlnjDbeH9vFTAFb5e3AdEBzzp9LOchkwLv0V/Fcdtfsr5AmSSBK44PfV84tOx69m
ydqrUgPS7SWrW1vRVNaX34twKZfO2TMBPyi4r3NTQiyk3Ij9l9QtK75lm8XGdw/I
bLR31cvlu54WM9qy9+8oTxJdw3LRPCgAkEqH46Ap6Ow2lHvK6tbpGMrfhkEHLxAC
1pi/n+S4br1rP2pNE8UpYHDB2dgGKvJGQ5diEhuHNRMT5x3kJQ9M89xqdlxXayF1
iJy1eyb40ofmh+3cJMTMPF6cMcpZU6poaPoYVgtSa8nttuObhSZUcr9rUG/P68Yc
EGc6waw0o1roXLB/HMMjn4m1IPDksF9vGfcom3LF7gLcDR/wiIkkZPvfydq8EfV+
u1S8i5vzLf5yEuStVENkx9AhwqJfFjrFkMV8oFoqRvFpViQsOzkxL1eAQLXkFN0n
1/9zS8tc1lCK1Q0UqE9w
=/OVK
-----END PGP SIGNATURE-----

**Comment by hlandau** [comment]
You can do what you like with your own branches.

**Comment by JeremyRand** [comment]
Removed WIP label, ready for review.

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/ncdns/pull/29/commits/1be990949d8a72ff489f265b830e566263aa753c

**Pull request merged**
