### PR TITLE
NSS TLS certificate injection

### PR DESCRIPTION
**Pull request by JeremyRand**
Extend #16 to support the user's shared NSS trust store on GNU/Linux systems.

Please review but do not merge yet.

TODO before merging:

- [x] Get #16 merged.
- [x] Figure out what to do in the case where ncdns isn't run by the same user as the owner of the NSS database.  Presumably it makes sense to run ncdns under its own user.  Should we require a config option that lists the users whose NSS databases are written to?

Other issue to discuss:

Writing to the NSS database with `certutil` is really slow, I'm seeing ~700ms latency added by this.  Is there a faster way to do it?  If we try to handle multiple NSS databases (one per user), this could easily cause DNS timeouts.  Using the system NSS database should be possible, but it would be unsafe for users who haven't installed the HPKP pin into Chromium.

### CODE REVIEW

**Comment by JeremyRand** [comment]
> Figure out what to do in the case where ncdns isn't run by the same user as the owner of the NSS database.

NSS cert database path is now a configurable option, so it doesn't try to auto-detect a directory based on user.

**Comment by JeremyRand** [comment]
Ready for review, although please don't merge until it passes Travis.  (We seem to have tripped an abuse detector at Travis recently, I'm waiting for that to be sorted out.)

**Comment by JeremyRand** [comment]
Working on fixing the Travis fails now.

**Comment by JeremyRand** [comment]
@hlandau Okay, I think this is ready for review now.  (I do intend to squash before merging.)

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/ncdns/pull/17/commits/3825487bacfe0a53ed74806b3ff8a616609821a2

**Comment by JeremyRand** [comment]
Squashed.

**Comment by JeremyRand** [comment]
I'll merge 375ff45a4d116866b7ef3bd0ff73d3ff2bd12989 once Travis finishes (assuming no issues show up in Travis).

**Pull request merged**
