### PR TITLE
generate_nmc_cert: rebase against Go 1.8.3 standard library.

### PR DESCRIPTION
**Pull request by JeremyRand**
~~Not yet tested; feel free to review/test but do not merge.~~

Ready for review, I think it's mergeable.

### CODE REVIEW

**Comment by JeremyRand** [comment]
Note that I'm NACKing the `gofmt -s` changes that `gometalinter` is asking for in this PR, because they needlessly clutter the patchset against upstream.  I'll probably have to mess with the Travis script to disable the `gofmt` linter for the `generate_nmc_cert` package (and probably also the `x509` package).

**Comment by JeremyRand** [comment]
No idea why the last 2 Travis builds stalled out; triggered a rebuild on Travis in the hope that it was a temporary issue that's fixed now.

**Comment by JeremyRand** [comment]
Ready for review, I think it's mergeable.  (I've verified that the cert rehydrates to the same DER encoding as the original; I haven't actually tried putting the generated cert+key into Nginx or anything like that.)

**Comment by hlandau** [comment]
Please remove commented code.

**Comment by JeremyRand** [comment]
> Please remove commented code.

@hlandau The commented code is deliberate; it makes it more straightforward to rebase against future Go versions.  Given that I'm the one who will probably be doing those future rebases, I request that the commented code stay intact.

**Comment by JeremyRand** [comment]
@hlandau Is this okay to merge?

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/ncdns/pull/54/commits/986772bd02c15d7d25dd8b86402cc3c497e76531

**Pull request merged**
