### PR TITLE
Fix build instructions for external x509

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/namecoin/ncdns/issues/109

### CODE REVIEW

**Comment by JeremyRand** [comment]
@loskiq Could you try this out and see if it fixes your issue?

**Comment by loskiq** [comment]
@JeremyRand thanks for your answer! I tried build ncdns again, but now another error:
```
root@ru:~/build# go get -d -t -u github.com/namecoin/ncdns/...
root@ru:~/build# go generate github.com/namecoin/x509-signature-splice/...
root@ru:~/build# go get -t github.com/namecoin/ncdns/...
../go/src/github.com/namecoin/x509-signature-splice/x509/x509.go:27:2: use of internal package internal/x/crypto/cryptobyte not allowed
../go/src/github.com/namecoin/x509-signature-splice/x509/x509.go:28:2: use of internal package internal/x/crypto/cryptobyte/asn1 not allowed
root@ru:~/build#
```

**Comment by JeremyRand** [comment]
@loskiq How about now?  (If it still doesn't work, can you tell me what version of Go you have?)

**Comment by JeremyRand** [comment]
This PR is definitely an improvement; merging.  @loskiq Please feel free to open a new issue if the issue you're experiencing isn't fixed.

**Pull request merged**
